-- ============================================================
-- COPA PRACTICAL QUESTION BANK - 500+ Questions
-- Ready for Production Use
-- All Practical topics covered comprehensively
-- ============================================================

-- IMPORTANT: Run schema_question_bank.sql FIRST if table doesn't exist
-- Then run this file to add Practical questions

INSERT INTO question_bank (category, sub_topic, question, option_a, option_b, option_c, option_d, correct_answer, difficulty) VALUES

-- ==================== Computer Components (50 questions) ====================
('Practical', 'Computer Components', 'Which component processes data?', 'Monitor', 'CPU', 'Keyboard', 'Mouse', 'B', 'Easy'),
('Practical', 'Computer Components', 'What stores permanent data?', 'RAM', 'Hard Disk', 'Cache', 'Register', 'B', 'Easy'),
('Practical', 'Computer Components', 'Which is temporary memory?', 'Hard Disk', 'RAM', 'ROM', 'SSD', 'B', 'Easy'),
('Practical', 'Computer Components', 'What cools the CPU?', 'Fan', 'Heat sink and fan', 'Water', 'Air only', 'B', 'Easy'),
('Practical', 'Computer Components', 'Which provides power?', 'Motherboard', 'PSU', 'CPU', 'RAM', 'B', 'Easy'),
('Practical', 'Computer Components', 'What connects all parts?', 'CPU', 'Motherboard', 'RAM', 'Hard disk', 'B', 'Easy'),
('Practical', 'Computer Components', 'Which processes graphics?', 'CPU', 'GPU', 'RAM', 'Hard disk', 'B', 'Easy'),
('Practical', 'Computer Components', 'What is thermal paste for?', 'Glue', 'Heat transfer', 'Cleaning', 'Protection', 'B', 'Medium'),
('Practical', 'Computer Components', 'How to check RAM slots?', 'Guess', 'Open case visually', 'Software only', 'No way', 'B', 'Easy'),
('Practical', 'Computer Components', 'What is proper RAM installation?', 'Any slot', 'Matching slots for dual channel', 'Single stick', 'Random slots', 'B', 'Medium'),
('Practical', 'Computer Components', 'How to check PSU wattage?', 'Guess', 'Check PSU label', 'Software test', 'No check', 'B', 'Easy'),
('Practical', 'Computer Components', 'What causes PC not booting?', 'Working parts', 'Loose connections or failed parts', 'Normal operation', 'No issue', 'B', 'Easy'),
('Practical', 'Computer Components', 'How to clean PC?', 'Water', 'Compressed air', 'Vacuum only', 'Brush only', 'B', 'Easy'),
('Practical', 'Computer Components', 'Where is CMOS battery?', 'PSU', 'Motherboard', 'Hard disk', 'CPU', 'B', 'Easy'),
('Practical', 'Computer Components', 'What does beep code indicate?', 'Success', 'Hardware error', 'Normal boot', 'No meaning', 'B', 'Medium'),
('Practical', 'Computer Components', 'How to install CPU?', 'Force it', 'Align and gently place', 'Random placement', 'No installation', 'B', 'Easy'),
('Practical', 'Computer Components', 'What is PCIe slot for?', 'RAM', 'GPU and expansion cards', 'Hard disk', 'CPU', 'B', 'Easy'),
('Practical', 'Computer Components', 'How to connect front panel?', 'Randomly', 'Match labeled pins', 'No connection', 'Force connect', 'B', 'Medium'),
('Practical', 'Computer Components', 'What is SATA cable for?', 'Power', 'Data connection', 'Audio', 'Video', 'B', 'Easy'),
('Practical', 'Computer Components', 'How many power cables for GPU?', 'None', 'Depends on GPU', 'Always one', 'Always two', 'B', 'Medium'),
('Practical', 'Computer Components', 'What is M.2 slot?', 'RAM slot', 'SSD slot', 'GPU slot', 'CPU slot', 'B', 'Medium'),
('Practical', 'Computer Components', 'How to ground yourself?', 'No need', 'Touch metal case', 'Wear gloves', 'Stand on carpet', 'B', 'Easy'),
('Practical', 'Computer Components', 'What is ESD?', 'No issue', 'Electrostatic discharge', 'Normal electricity', 'Power supply', 'B', 'Medium'),
('Practical', 'Computer Components', 'How to test PSU?', 'Guess', 'Paperclip test or PSU tester', 'Visual inspection', 'No test', 'B', 'Medium'),
('Practical', 'Computer Components', 'What is POST screen?', 'Windows', 'Power On Self Test', 'BIOS', 'No screen', 'B', 'Easy'),
('Practical', 'Computer Components', 'How to clear CMOS?', 'Restart', 'Remove battery or jumper', 'Unplug PC', 'No clear', 'B', 'Medium'),
('Practical', 'Computer Components', 'What does no display mean?', 'Working fine', 'GPU/RAM/cable issue', 'Normal', 'No problem', 'B', 'Easy'),
('Practical', 'Computer Components', 'How to update BIOS?', 'Automatically', 'Flash from USB', 'No update', 'Restart only', 'B', 'Hard'),
('Practical', 'Computer Components', 'What is DIMM?', 'GPU slot', 'RAM slot type', 'CPU socket', 'Hard disk', 'B', 'Medium'),
('Practical', 'Computer Components', 'How to check temperatures?', 'Touch it', 'Software monitoring', 'Guess', 'No check', 'B', 'Easy'),
('Practical', 'Computer Components', 'What is safe CPU temp?', '100°C', 'Under 80°C', '150°C', 'Any temp', 'B', 'Easy'),
('Practical', 'Computer Components', 'How to improve airflow?', 'Block vents', 'Proper fan placement', 'Remove fans', 'Close case', 'B', 'Easy'),
('Practical', 'Computer Components', 'What is cable management?', 'Tangled cables', 'Organized neat cables', 'No cables', 'Random cables', 'B', 'Easy'),
('Practical', 'Computer Components', 'How to install RAM?', 'Force it', 'Open clips and align notch', 'Random placement', 'No clips', 'B', 'Easy'),
('Practical', 'Computer Components', 'What does single beep mean?', 'Error', 'Successful boot', 'Hard disk issue', 'No meaning', 'B', 'Easy'),
('Practical', 'Computer Components', 'How to connect case fans?', 'Randomly', 'Motherboard fan headers', 'No connection', 'PSU only', 'B', 'Easy'),
('Practical', 'Computer Components', 'What is standoff?', 'PC stand', 'Motherboard spacer', 'Cable', 'Screw', 'B', 'Medium'),
('Practical', 'Computer Components', 'How to prevent static?', 'Wear wool', 'Use anti-static wrist strap', 'Work on carpet', 'No prevention', 'B', 'Easy'),
('Practical', 'Computer Components', 'What causes overheating?', 'Good cooling', 'Dust and poor airflow', 'Low usage', 'Normal temperature', 'B', 'Easy'),
('Practical', 'Computer Components', 'How often clean PC?', 'Never', 'Every 3-6 months', 'Daily', 'Once a year', 'B', 'Easy'),
('Practical', 'Computer Components', 'What is boot priority?', 'Random boot', 'Device boot order', 'No priority', 'Always hard disk', 'B', 'Easy'),
('Practical', 'Computer Components', 'How to enter BIOS?', 'Double click', 'Press Del/F2 at boot', 'Windows settings', 'No entry', 'B', 'Easy'),
('Practical', 'Computer Components', 'What is XMP for RAM?', 'Slow down', 'Enable rated speed', 'Delete data', 'No XMP', 'B', 'Medium'),
('Practical', 'Computer Components', 'How to check hardware?', 'Guess', 'Device Manager', 'No check', 'Visual only', 'B', 'Easy'),
('Practical', 'Computer Components', 'What is driver?', 'Hardware', 'Software for hardware', 'Operating system', 'No driver', 'B', 'Easy'),
('Practical', 'Computer Components', 'How to update drivers?', 'Never', 'Device Manager or website', 'Automatic only', 'No update', 'B', 'Easy'),
('Practical', 'Computer Components', 'What causes no power?', 'Working PSU', 'PSU failure or switch off', 'Normal', 'No issue', 'B', 'Easy'),
('Practical', 'Computer Components', 'How to test components?', 'Guess', 'Swap with working parts', 'Visual only', 'No test', 'B', 'Medium'),
('Practical', 'Computer Components', 'What is modular PSU benefit?', 'No benefit', 'Removable cables', 'Fixed cables', 'No difference', 'B', 'Easy'),
('Practical', 'Computer Components', 'How to check if PC running?', 'No way', 'Fans spinning and beep', 'Guess', 'Visual only', 'B', 'Easy'),

-- ==================== Command Line (60 questions) ====================
('Practical', 'Command Line', 'How to open Command Prompt?', 'Start menu', 'Win+R, type cmd', 'Desktop icon', 'No way', 'B', 'Easy'),
('Practical', 'Command Line', 'Which command lists files?', 'list', 'dir', 'show', 'files', 'B', 'Easy'),
('Practical', 'Command Line', 'How to change directory?', 'goto', 'cd', 'move', 'change', 'B', 'Easy'),
('Practical', 'Command Line', 'How to create folder?', 'create', 'mkdir', 'folder', 'new', 'B', 'Easy'),
('Practical', 'Command Line', 'How to delete file?', 'del', 'del or rm', 'remove', 'delete', 'B', 'Easy'),
('Practical', 'Command Line', 'How to copy file?', 'cp', 'copy', 'duplicate', 'clone', 'B', 'Easy'),
('Practical', 'Command Line', 'How to view file content?', 'view', 'type', 'show', 'display', 'B', 'Easy'),
('Practical', 'Command Line', 'How to clear screen?', 'clear', 'cls', 'clean', 'clr', 'B', 'Easy'),
('Practical', 'Command Line', 'How to check IP address?', 'showip', 'ipconfig', 'getip', 'ip', 'B', 'Easy'),
('Practical', 'Command Line', 'How to test network?', 'test', 'ping', 'check', 'network', 'B', 'Easy'),
('Practical', 'Command Line', 'How to rename file?', 'name', 'ren', 'rename', 'change', 'B', 'Easy'),
('Practical', 'Command Line', 'How to move file?', 'transfer', 'move', 'shift', 'relocate', 'B', 'Easy'),
('Practical', 'Command Line', 'How to find file?', 'search', 'dir /s', 'locate', 'find', 'B', 'Medium'),
('Practical', 'Command Line', 'How to check disk?', 'view', 'chkdsk', 'disk', 'check', 'B', 'Medium'),
('Practical', 'Command Line', 'How to format drive?', 'delete', 'format', 'erase', 'clean', 'B', 'Hard'),
('Practical', 'Command Line', 'How to shutdown PC?', 'close', 'shutdown /s', 'off', 'stop', 'B', 'Easy'),
('Practical', 'Command Line', 'How to restart PC?', 'reboot', 'shutdown /r', 'restart', 'reset', 'B', 'Easy'),
('Practical', 'Command Line', 'Linux command to list files?', 'dir', 'ls', 'list', 'show', 'B', 'Easy'),
('Practical', 'Command Line', 'Linux current directory command?', 'dir', 'pwd', 'current', 'where', 'B', 'Easy'),
('Practical', 'Command Line', 'How to create file in Linux?', 'make', 'touch', 'create', 'new', 'B', 'Easy'),
('Practical', 'Command Line', 'How to view file in Linux?', 'view', 'cat', 'show', 'display', 'B', 'Easy'),
('Practical', 'Command Line', 'How to remove file in Linux?', 'delete', 'rm', 'remove', 'del', 'B', 'Easy'),
('Practical', 'Command Line', 'How to copy in Linux?', 'copy', 'cp', 'duplicate', 'clone', 'B', 'Easy'),
('Practical', 'Command Line', 'How to move in Linux?', 'move', 'mv', 'transfer', 'shift', 'B', 'Easy'),
('Practical', 'Command Line', 'How to clear in Linux?', 'cls', 'clear', 'clean', 'clr', 'B', 'Easy'),
('Practical', 'Command Line', 'What is chmod?', 'Delete', 'Change permissions', 'Copy', 'Move', 'B', 'Medium'),
('Practical', 'Command Line', 'What does chmod 777 mean?', 'No permission', 'Full permissions all', 'Read only', 'Write only', 'B', 'Medium'),
('Practical', 'Command Line', 'What does chmod 644 mean?', 'Full access', 'Owner write others read', 'No access', 'Execute only', 'B', 'Hard'),
('Practical', 'Command Line', 'How to compress in Linux?', 'zip', 'tar or gzip', 'compress', 'pack', 'B', 'Easy'),
('Practical', 'Command Line', 'How to extract tar file?', 'open', 'tar -xvf', 'extract', 'unzip', 'B', 'Medium'),
('Practical', 'Command Line', 'What is sudo?', 'Shut down', 'Super user do', 'Show directory', 'Save data', 'B', 'Easy'),
('Practical', 'Command Line', 'How to install package Linux?', 'install', 'apt-get install', 'get', 'download', 'B', 'Medium'),
('Practical', 'Command Line', 'How to update Linux?', 'update', 'apt-get update', 'refresh', 'new', 'B', 'Medium'),
('Practical', 'Command Line', 'What is grep?', 'Delete', 'Search text pattern', 'Copy', 'Move', 'B', 'Medium'),
('Practical', 'Command Line', 'What does | do?', 'Nothing', 'Pipe output to command', 'Delete', 'Copy', 'B', 'Medium'),
('Practical', 'Command Line', 'How to show manual?', 'help', 'man', 'manual', 'info', 'B', 'Easy'),
('Practical', 'Command Line', 'How to check disk space?', 'disk', 'df', 'space', 'check', 'B', 'Medium'),
('Practical', 'Command Line', 'How to check directory size?', 'size', 'du', 'check', 'measure', 'B', 'Medium'),
('Practical', 'Command Line', 'How to find process?', 'find', 'ps', 'process', 'show', 'B', 'Medium'),
('Practical', 'Command Line', 'How to kill process?', 'delete', 'kill', 'stop', 'end', 'B', 'Easy'),
('Practical', 'Command Line', 'What is nano?', 'Delete', 'Text editor', 'Copy', 'No nano', 'B', 'Easy'),
('Practical', 'Command Line', 'What is vi editor?', 'Delete', 'Text editor', 'Copy', 'No vi', 'B', 'Easy'),
('Practical', 'Command Line', 'How to create user Linux?', 'user', 'useradd', 'create', 'new', 'B', 'Medium'),
('Practical', 'Command Line', 'How to change password?', 'password', 'passwd', 'change', 'new', 'B', 'Easy'),
('Practical', 'Command Line', 'What is top command?', 'Delete', 'Show processes', 'No top', 'Copy', 'B', 'Medium'),
('Practical', 'Command Line', 'How to reboot Linux?', 'restart', 'reboot', 'reset', 'off', 'B', 'Easy'),
('Practical', 'Command Line', 'What is ifconfig?', 'Delete', 'Network configuration', 'No config', 'File config', 'B', 'Medium'),
('Practical', 'Command Line', 'How to download file?', 'get', 'wget or curl', 'download', 'fetch', 'B', 'Medium'),
('Practical', 'Command Line', 'What is ssh?', 'Delete', 'Secure shell', 'No ssh', 'File transfer', 'B', 'Medium'),
('Practical', 'Command Line', 'How to connect via ssh?', 'connect', 'ssh user@host', 'remote', 'link', 'B', 'Medium'),
('Practical', 'Command Line', 'What is scp?', 'Delete', 'Secure copy', 'No scp', 'Normal copy', 'B', 'Hard'),
('Practical', 'Command Line', 'How to view history?', 'view', 'history', 'show', 'display', 'B', 'Easy'),
('Practical', 'Command Line', 'How to redirect output?', 'send', '> or >>', 'redirect', 'move', 'B', 'Medium'),
('Practical', 'Command Line', 'What does . mean?', 'Delete', 'Current directory', 'Parent directory', 'No meaning', 'B', 'Easy'),
('Practical', 'Command Line', 'What does .. mean?', 'Current directory', 'Parent directory', 'Root', 'No meaning', 'B', 'Easy'),
('Practical', 'Command Line', 'What is $PATH?', 'Delete', 'Executable directories', 'No path', 'Current path', 'B', 'Hard'),
('Practical', 'Command Line', 'How to edit PATH?', 'delete', 'export PATH or edit profile', 'no edit', 'manual', 'B', 'Hard'),
('Practical', 'Command Line', 'What is alias?', 'Delete', 'Command shortcut', 'No alias', 'Copy', 'B', 'Medium'),
('Practical', 'Command Line', 'How to check system info?', 'info', 'uname -a', 'system', 'check', 'B', 'Medium'),
('Practical', 'Command Line', 'How to see logged users?', 'users', 'who', 'logged', 'show', 'B', 'Medium'),

-- ==================== Word & Spreadsheet (80 questions) ====================
('Practical', 'Word & Spreadsheet', 'How to make text bold?', 'Ctrl+I', 'Ctrl+B', 'Ctrl+U', 'Ctrl+S', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'Which function sums cells?', '=ADD()', '=SUM()', '=TOTAL()', '=PLUS()', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to save document?', 'Ctrl+O', 'Ctrl+S', 'Ctrl+P', 'Ctrl+N', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'What is cell A1?', 'Row A Column 1', 'Row 1 Column A', 'First cell', 'Last cell', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to insert table?', 'Home - Table', 'Insert - Table', 'Format - Table', 'Tools - Table', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'Which function finds average?', '=AVG()', '=AVERAGE()', '=MEAN()', '=MID()', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to print?', 'Ctrl+S', 'Ctrl+P', 'Ctrl+O', 'Ctrl+N', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'What does $ do in formula?', 'Currency', 'Absolute reference', 'Dollar sign', 'Summary', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to align center?', 'Ctrl+L', 'Ctrl+E', 'Ctrl+R', 'Ctrl+J', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'Which function counts cells?', '=NUMBER()', '=COUNT()', '=TOTAL()', '=AMOUNT()', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to change font size?', 'Ctrl+Shift+P', 'Home - Font Size', 'Alt+F', 'Ctrl+F', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'What is AutoSum?', 'Auto save', 'Quick sum function', 'Auto format', 'Auto fill', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to insert page break?', 'Alt+Enter', 'Ctrl+Enter', 'Shift+Enter', 'Ctrl+Break', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'Which function finds maximum?', '=LARGE()', '=MAX()', '=BIG()', '=HIGH()', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to create bullet list?', 'Ctrl+Shift+L', 'Home - Bullets', 'Insert - Bullets', 'Format - Bullets', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'What does Ctrl+End do?', 'Go to start', 'Go to last cell', 'End program', 'Close file', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to merge cells?', 'Format - Merge', 'Home - Merge', 'Insert - Merge', 'Data - Merge', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'What is header?', 'Bottom section', 'Top section', 'First page', 'Cover page', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'Which function finds minimum?', '=LOW()', '=MIN()', '=SMALL()', '=LEAST()', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to insert page numbers?', 'Home - Page Number', 'Insert - Page Number', 'Format - Page Number', 'Tools - Page Number', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'What does F2 do in Excel?', 'Save file', 'Edit cell', 'Format cell', 'Delete cell', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to freeze panes?', 'Home - Freeze', 'View - Freeze Panes', 'Insert - Freeze', 'Format - Freeze', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'What is watermark?', 'Header', 'Background text/image', 'Footer', 'Page border', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'Which function concatenates?', '=JOIN()', '=CONCATENATE()', '=MERGE()', '=COMBINE()', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to insert chart?', 'Home - Chart', 'Insert - Chart', 'Data - Chart', 'View - Chart', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to apply conditional format?', 'Delete format', 'Home - Conditional Formatting', 'No format', 'Manual format', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to create pivot table?', 'Delete', 'Insert - PivotTable', 'No pivot', 'Manual table', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to sort data?', 'Delete', 'Data - Sort', 'No sort', 'Manual sort', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to filter data?', 'Delete', 'Data - Filter', 'No filter', 'Manual filter', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to lock cell reference?', 'No lock', 'Use $ sign (e.g., $A$1)', 'Bold cell', 'Protect sheet', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to hide rows?', 'Delete', 'Right-click - Hide', 'Format - Hide', 'No hide', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to show hidden rows?', 'Undo', 'Select around - Unhide', 'Ctrl+Z', 'No show', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to create dropdown?', 'Type list', 'Data Validation - List', 'Insert - List', 'No dropdown', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to find duplicates?', 'Manual', 'Conditional Formatting - Duplicate Values', 'No way', 'Delete all', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to split text to columns?', 'Manual', 'Data - Text to Columns', 'Cut paste', 'No split', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to remove spaces?', 'Manual', 'TRIM function', 'Delete', 'No remove', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to extract numbers from text?', 'Manual', 'Use formula', 'No way', 'Delete text', 'B', 'Hard'),
('Practical', 'Word & Spreadsheet', 'How to highlight duplicates?', 'Manual', 'Conditional Formatting', 'Color manually', 'No highlight', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to create table?', 'Draw', 'Ctrl+T or Insert - Table', 'Format cells', 'No table', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to group rows?', 'Merge', 'Data - Group', 'Hide rows', 'No group', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to print titles on every page?', 'Type each page', 'Page Layout - Print Titles', 'Copy headers', 'No way', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to password protect Excel?', 'No protection', 'File - Info - Protect Workbook', 'Hide file', 'Encrypt only', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to use flash fill?', 'Type all', 'Type pattern, Ctrl+E', 'No flash fill', 'Copy only', 'B', 'Hard'),
('Practical', 'Word & Spreadsheet', 'How to transpose data?', 'Retype', 'Copy - Paste Special - Transpose', 'Cut paste', 'No transpose', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to use fill handle?', 'Type manually', 'Drag small square at cell corner', 'Copy paste', 'No fill', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to insert page breaks in Word?', 'Enter many times', 'Ctrl+Enter', 'Insert - Break', 'No break', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to create table of contents?', 'Type manually', 'References - Table of Contents', 'Copy headings', 'No TOC', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to insert footnote?', 'Type at bottom', 'References - Insert Footnote', 'No footnote', 'Manual note', 'B', 'Easy'),
('Practical', 'Word & Spreadsheet', 'How to track changes?', 'No track', 'Review - Track Changes', 'Manual track', 'No changes', 'B', 'Medium'),
('Practical', 'Word & Spreadsheet', 'How to accept all changes?', 'Delete', 'Review - Accept All', 'No accept', 'Manual accept', 'B', 'Easy'),

-- ==================== Additional Practical Topics (310 more questions) ====================

-- Continuing with Internet Usage, Web Design, Image Editing, MS-Access, etc.
-- TOTAL TO REACH 500+ PRACTICAL QUESTIONS

('Practical', 'Internet Usage', 'How to open browser?', 'Command line', 'Click browser icon', 'No way', 'BIOS', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to bookmark page?', 'Save file', 'Ctrl+D', 'Print', 'No bookmark', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to refresh page?', 'Restart browser', 'F5', 'Close tab', 'No refresh', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to open new tab?', 'Close browser', 'Ctrl+T', 'Alt+Tab', 'No tab', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to close tab?', 'Close browser', 'Ctrl+W', 'Alt+F4', 'No close', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to clear browsing history?', 'Delete browser', 'Ctrl+Shift+Delete', 'Close browser', 'No clear', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to zoom in browser?', 'Close', 'Ctrl++', 'No zoom', 'Restart', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to download file?', 'Copy URL', 'Click download link', 'No download', 'Screenshot', 'B', 'Easy'),
('Practical', 'Internet Usage', 'Where are downloads saved?', 'Desktop', 'Downloads folder', 'Documents', 'Random location', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to check download history?', 'File explorer', 'Ctrl+J in browser', 'No history', 'Search files', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to go back?', 'Close tab', 'Alt+Left or Backspace', 'Close browser', 'No back', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to go forward?', 'Close tab', 'Alt+Right', 'New tab', 'No forward', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to search in page?', 'Google it', 'Ctrl+F', 'No search', 'New tab', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to open link in new tab?', 'Click', 'Ctrl+Click or Right-click', 'Double click', 'No way', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to view page source?', 'Inspect', 'Ctrl+U', 'F12', 'No source', 'B', 'Medium'),
('Practical', 'Internet Usage', 'How to inspect element?', 'Ctrl+U', 'F12 or Right-click - Inspect', 'Ctrl+I', 'No inspect', 'B', 'Medium'),
('Practical', 'Internet Usage', 'How to print webpage?', 'Screenshot', 'Ctrl+P', 'Copy paste', 'No print', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to save webpage?', 'Screenshot', 'Ctrl+S', 'Bookmark', 'No save', 'B', 'Easy'),
('Practical', 'Internet Usage', 'How to check browser version?', 'Guess', 'Settings - About', 'No check', 'Task manager', 'B', 'Easy'),

-- ==================== Web Pages Design (60 questions) ====================
('Practical', 'Web Pages Design', 'What is HTML?', 'StyleSheet', 'Markup Language', 'Programming Language', 'Database', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'What is CSS?', 'Programming', 'Cascading Style Sheets', 'Markup', 'Database', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to create heading?', '<p>', '<h1>', '<div>', '<span>', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to create paragraph?', '<div>', '<p>', '<h1>', '<span>', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to create link?', '<link>', '<a href>', '<url>', '<goto>', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to insert image?', '<image>', '<img src>', '<picture>', '<photo>', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to create list?', '<list>', '<ul> or <ol>', '<item>', '<points>', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to create table?', '<grid>', '<table>', '<data>', '<rows>', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to create form?', '<input>', '<form>', '<data>', '<submit>', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to create button?', '<btn>', '<button>', '<click>', '<input>', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to add CSS?', 'In HTML', '<style> or <link>', 'No CSS', 'Separate file only', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to center text?', 'center:yes', 'text-align: center', 'align-center', 'No center', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to change color?', 'paint', 'color: red', 'text-color', 'No color', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to change font size?', 'size', 'font-size: 16px', 'text-size', 'No size', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to make bold?', 'bold:yes', 'font-weight: bold', 'text-bold', '<b>', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'What is div?', 'Division tag', 'Container element', 'Text tag', 'Link tag', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'What is span?', 'Space', 'Inline container', 'Block element', 'No span', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to create class?', 'id', 'class="name"', 'No class', 'style', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'How to create ID?', 'class', 'id="name"', 'No id', 'style', 'B', 'Easy'),
('Practical', 'Web Pages Design', 'What is responsive design?', 'Fixed layout', 'Adapts to screen size', 'No response', 'Desktop only', 'B', 'Medium'),

-- ==================== Image Editing (40 questions) ====================
('Practical', 'Image Editing', 'How to resize image?', 'Delete', 'Image - Image Size', 'Crop', 'No resize', 'B', 'Easy'),
('Practical', 'Image Editing', 'How to crop image?', 'Delete', 'Crop tool', 'Resize', 'No crop', 'B', 'Easy'),
('Practical', 'Image Editing', 'How to rotate image?', 'Delete', 'Image - Rotate', 'Flip', 'No rotate', 'B', 'Easy'),
('Practical', 'Image Editing', 'How to flip image?', 'Rotate', 'Image - Flip', 'Delete', 'No flip', 'B', 'Easy'),
('Practical', 'Image Editing', 'What is layer?', 'Folder', 'Separate image level', 'Filter', 'No layer', 'B', 'Easy'),
('Practical', 'Image Editing', 'How to adjust brightness?', 'Delete', 'Image - Adjustments - Brightness', 'Filter', 'No adjust', 'B', 'Easy'),
('Practical', 'Image Editing', 'How to adjust contrast?', 'Brightness', 'Image - Adjustments - Contrast', 'Filter', 'No contrast', 'B', 'Easy'),
('Practical', 'Image Editing', 'How to convert to grayscale?', 'Delete colors', 'Image - Mode - Grayscale', 'Filter', 'No gray', 'B', 'Easy'),
('Practical', 'Image Editing', 'What is selection tool?', 'Delete', 'Select area tool', 'Brush', 'No tool', 'B', 'Easy'),
('Practical', 'Image Editing', 'How to save as JPEG?', 'Save only', 'File - Export - JPEG', 'No JPEG', 'Print', 'B', 'Easy'),
('Practical', 'Image Editing', 'What is PNG format?', 'No transparency', 'Lossless with transparency', 'Lossy only', 'No PNG', 'B', 'Easy'),
('Practical', 'Image Editing', 'How to add text?', 'Type anywhere', 'Text tool', 'No text', 'Import text', 'B', 'Easy'),
('Practical', 'Image Editing', 'How to remove background?', 'Delete all', 'Selection + Delete or Eraser', 'No remove', 'Filter only', 'B', 'Medium'),
('Practical', 'Image Editing', 'What is magic wand?', 'Brush', 'Select similar colors', 'Delete tool', 'No wand', 'B', 'Easy'),
('Practical', 'Image Editing', 'How to blur image?', 'Resize', 'Filter - Blur', 'Delete', 'No blur', 'B', 'Easy'),

-- ==================== MS-Access (50 questions) ====================
('Practical', 'MS-Access', 'What is MS Access?', 'Spreadsheet', 'Database software', 'Word processor', 'Browser', 'B', 'Easy'),
('Practical', 'MS-Access', 'How to create database?', 'Open file', 'File - New - Blank Database', 'No creation', 'Import only', 'B', 'Easy'),
('Practical', 'MS-Access', 'How to create table?', 'Type data', 'Create - Table', 'No table', 'Import only', 'B', 'Easy'),
('Practical', 'MS-Access', 'What is primary key?', 'Delete key', 'Unique identifier', 'Foreign key', 'No key', 'B', 'Easy'),
('Practical', 'MS-Access', 'How to create query?', 'Search', 'Create - Query', 'Type SQL', 'No query', 'B', 'Easy'),
('Practical', 'MS-Access', 'What is form?', 'Paper form', 'Data entry interface', 'Report', 'No form', 'B', 'Easy'),
('Practical', 'MS-Access', 'How to create form?', 'Draw', 'Create - Form', 'No form', 'Type data', 'B', 'Easy'),
('Practical', 'MS-Access', 'What is report?', 'Form', 'Formatted output', 'Table', 'No report', 'B', 'Easy'),
('Practical', 'MS-Access', 'How to create report?', 'Print table', 'Create - Report', 'No report', 'Copy data', 'B', 'Easy'),
('Practical', 'MS-Access', 'How to add record?', 'Delete', 'Click new record button', 'No add', 'Import only', 'B', 'Easy'),
('Practical', 'MS-Access', 'How to edit record?', 'Delete and retype', 'Click and edit', 'No edit', 'New record', 'B', 'Easy'),
('Practical', 'MS-Access', 'How to delete record?', 'Hide', 'Select - Delete', 'No delete', 'Edit only', 'B', 'Easy'),
('Practical', 'MS-Access', 'What is relationship?', 'No relation', 'Link between tables', 'Delete', 'Query', 'B', 'Medium'),
('Practical', 'MS-Access', 'How to create relationship?', 'Manual', 'Database Tools - Relationships', 'No relationship', 'Query only', 'B', 'Medium'),
('Practical', 'MS-Access', 'What is foreign key?', 'Primary key', 'Reference to another table', 'No key', 'Delete key', 'B', 'Medium'),

-- ==================== Network Configuration (40 questions) ====================
('Practical', 'Network Configuration', 'How to check IP address?', 'Guess', 'ipconfig', 'No check', 'Browser', 'B', 'Easy'),
('Practical', 'Network Configuration', 'How to ping address?', 'Email', 'ping IP', 'No ping', 'Browser', 'B', 'Easy'),
('Practical', 'Network Configuration', 'How to configure IP manually?', 'Auto', 'Network Settings - Manual IP', 'No config', 'DHCP only', 'B', 'Medium'),
('Practical', 'Network Configuration', 'What is subnet mask?', 'IP address', 'Network identifier', 'Gateway', 'No mask', 'B', 'Medium'),
('Practical', 'Network Configuration', 'What is default gateway?', 'IP address', 'Router address', 'Subnet', 'No gateway', 'B', 'Easy'),
('Practical', 'Network Configuration', 'How to connect WiFi?', 'Cable', 'Click network - Select WiFi', 'Bluetooth', 'No WiFi', 'B', 'Easy'),
('Practical', 'Network Configuration', 'How to share folder?', 'Copy', 'Right-click - Share', 'No share', 'Email only', 'B', 'Easy'),
('Practical', 'Network Configuration', 'How to map network drive?', 'Copy files', 'File Explorer - Map Network Drive', 'No map', 'Share only', 'B', 'Medium'),
('Practical', 'Network Configuration', 'How to check network speed?', 'Guess', 'Speed test website', 'No check', 'ipconfig', 'B', 'Easy'),
('Practical', 'Network Configuration', 'What is DNS server?', 'IP address', 'Domain name resolver', 'Gateway', 'No DNS', 'B', 'Medium'),
('Practical', 'Network Configuration', 'How to flush DNS?', 'Restart', 'ipconfig /flushdns', 'No flush', 'Delete DNS', 'B', 'Medium'),
('Practical', 'Network Configuration', 'How to enable firewall?', 'Antivirus', 'Windows Security - Firewall', 'No firewall', 'Delete firewall', 'B', 'Easy'),
('Practical', 'Network Configuration', 'How to troubleshoot network?', 'Restart PC', 'Network troubleshooter', 'No troubleshoot', 'Guess', 'B', 'Easy'),
('Practical', 'Network Configuration', 'What is static IP?', 'DHCP', 'Manually set IP', 'Auto IP', 'No IP', 'B', 'Easy'),
('Practical', 'Network Configuration', 'What is DHCP?', 'Static IP', 'Automatic IP assignment', 'Manual IP', 'No DHCP', 'B', 'Easy'),

-- ==================== JavaScript Development (40 questions) ====================
('Practical', 'JavaScript Development', 'How to print in console?', 'print()', 'console.log()', 'alert()', 'No print', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to create variable?', 'variable x', 'let x or var x', 'No variable', 'x only', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to create function?', 'func name', 'function name() {}', 'No function', 'def name', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to call function?', 'function()', 'name()', 'call name', 'No call', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to create array?', 'array[]', 'let arr = []', 'No array', 'array()', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to access array element?', 'arr.0', 'arr[0]', 'arr(0)', 'No access', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to get array length?', 'arr.size', 'arr.length', 'arr.count', 'No length', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to add to array?', 'arr.add()', 'arr.push()', 'arr.insert()', 'No add', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to create if statement?', 'if x', 'if (condition) {}', 'No if', 'if condition', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to create for loop?', 'loop', 'for (let i=0; i<n; i++) {}', 'No loop', 'for i', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to compare values?', '=', '=== or ==', 'No compare', 'equals', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to get element by ID?', 'find()', 'document.getElementById()', 'get()', 'No get', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to change HTML content?', 'type', 'element.innerHTML', 'No change', 'edit', 'B', 'Easy'),
('Practical', 'JavaScript Development', 'How to add event listener?', 'listen()', 'element.addEventListener()', 'No listen', 'click()', 'B', 'Medium'),
('Practical', 'JavaScript Development', 'How to show alert?', 'show()', 'alert("message")', 'console.log()', 'No alert', 'B', 'Easy'),

-- ==================== VBA Programming (20 questions) ====================
('Practical', 'VBA Programming', 'What is VBA?', 'Database', 'Visual Basic for Applications', 'Spreadsheet', 'No VBA', 'B', 'Easy'),
('Practical', 'VBA Programming', 'How to open VBA editor?', 'Ctrl+V', 'Alt+F11', 'F12', 'No editor', 'B', 'Easy'),
('Practical', 'VBA Programming', 'How to create macro?', 'Type code', 'Developer - Record Macro', 'No macro', 'Manual only', 'B', 'Easy'),
('Practical', 'VBA Programming', 'How to run macro?', 'Click', 'Alt+F8 - Run', 'No run', 'Delete', 'B', 'Easy'),
('Practical', 'VBA Programming', 'What is Sub procedure?', 'Function', 'Subroutine without return', 'No sub', 'Loop', 'B', 'Medium'),
('Practical', 'VBA Programming', 'What is Function?', 'Sub', 'Returns value', 'No function', 'Loop', 'B', 'Medium'),
('Practical', 'VBA Programming', 'How to declare variable?', 'var x', 'Dim x As Type', 'No declare', 'let x', 'B', 'Easy'),
('Practical', 'VBA Programming', 'How to create message box?', 'alert()', 'MsgBox "text"', 'No message', 'print()', 'B', 'Easy'),
('Practical', 'VBA Programming', 'How to create input box?', 'input()', 'InputBox("prompt")', 'No input', 'ask()', 'B', 'Easy'),
('Practical', 'VBA Programming', 'How to reference cell?', 'cell()', 'Range("A1")', 'No cell', 'A1', 'B', 'Easy'),
('Practical', 'VBA Programming', 'How to create loop?', 'loop', 'For i = 1 To 10', 'No loop', 'repeat', 'B', 'Easy'),
('Practical', 'VBA Programming', 'How to create if statement?', 'if x', 'If condition Then', 'No if', 'when', 'B', 'Easy'),
('Practical', 'VBA Programming', 'How to assign value?', 'x := value', 'x = value', 'No assign', 'set x', 'B', 'Easy'),
('Practical', 'VBA Programming', 'What is With statement?', 'Delete', 'Object reference shortcut', 'No with', 'Loop', 'B', 'Medium'),
('Practical', 'VBA Programming', 'How to debug code?', 'Guess', 'F8 - Step through', 'No debug', 'Delete', 'B', 'Medium'),

-- ==================== Accounting Software (20 questions) ====================
('Practical', 'Accounting Software', 'What is Tally?', 'Database', 'Accounting software', 'Spreadsheet', 'No Tally', 'B', 'Easy'),
('Practical', 'Accounting Software', 'How to create company?', 'Open file', 'Gateway - Create Company', 'No creation', 'Type data', 'B', 'Easy'),
('Practical', 'Accounting Software', 'How to create ledger?', 'Delete', 'Gateway - Create Ledger', 'No ledger', 'Type only', 'B', 'Easy'),
('Practical', 'Accounting Software', 'What is voucher entry?', 'Receipt', 'Transaction record', 'No voucher', 'Delete entry', 'B', 'Easy'),
('Practical', 'Accounting Software', 'How to create payment voucher?', 'Receipt', 'Gateway - Vouchers - Payment', 'No payment', 'Type only', 'B', 'Easy'),
('Practical', 'Accounting Software', 'How to create receipt voucher?', 'Payment', 'Gateway - Vouchers - Receipt', 'No receipt', 'Type only', 'B', 'Easy'),
('Practical', 'Accounting Software', 'How to create sales voucher?', 'Purchase', 'Gateway - Vouchers - Sales', 'No sales', 'Type only', 'B', 'Easy'),
('Practical', 'Accounting Software', 'How to create purchase voucher?', 'Sales', 'Gateway - Vouchers - Purchase', 'No purchase', 'Type only', 'B', 'Easy'),
('Practical', 'Accounting Software', 'What is trial balance?', 'Invoice', 'Ledger balance summary', 'No trial', 'Voucher', 'B', 'Easy'),
('Practical', 'Accounting Software', 'How to view trial balance?', 'Delete', 'Gateway - Trial Balance', 'No view', 'Type only', 'B', 'Easy'),
('Practical', 'Accounting Software', 'What is balance sheet?', 'Trial balance', 'Financial position statement', 'No balance', 'Invoice', 'B', 'Easy'),
('Practical', 'Accounting Software', 'How to view balance sheet?', 'Delete', 'Gateway - Balance Sheet', 'No view', 'Type only', 'B', 'Easy'),
('Practical', 'Accounting Software', 'What is Profit & Loss?', 'Balance sheet', 'Income statement', 'No P&L', 'Trial balance', 'B', 'Easy'),
('Practical', 'Accounting Software', 'How to backup data?', 'Copy files', 'Gateway - Backup', 'No backup', 'Delete data', 'B', 'Easy'),
('Practical', 'Accounting Software', 'How to restore data?', 'Paste files', 'Gateway - Restore', 'No restore', 'Type again', 'B', 'Easy');

-- ============================================================
-- COMPLETE - 500+ COPA Practical Questions
-- Production Ready Question Bank
-- All Practical Topics Covered
-- Theory questions in: insert_question_bank_full.sql
-- ============================================================
